### ISSUE TITLE
Set oddTeamStyles via CSS instead of inline styles?

### ISSUE THREAD

**Issue by pdehaan** [christiannwamba/universal-landing#2]
Although, you'd also have to update the chapter, so maybe isn't worth the effort.

https://github.com/christiannwamba/universal-landing/blob/1653658b6da0595fa8ef542d6d6abee72e03e954/components/Team.js#L4-L11

Instead of using inline styles, I think you could also just do this w/ CSS using `:nth-child()`:

```css
.Team:nth-child(even) {
  flex-direction: row-reverse;
  text-align: right;
}

.Team:nth-child(odd) {
  flex-direction: row;
  text-align: left;
}
```

... And you may not even need both `odd` and `even` if you set a default `flex-direction` and `text-align` in the `.Team{}` rule, and then just override the alternating `:nth-child(even) {}` values: 

```
.Team {
  display: flex;
  align-items: center;
  margin-bottom: 20px;
  background: #fff;
  padding: 15px;
  flex-direction: row;
  text-align: left;
}

.Team:nth-child(even) {
  flex-direction: row-reverse;
  text-align: right;
}
```
